# Field Constants
FIELD_MONTH = "Month"
FIELD_YEAR = "Year"

# Roster
FIELD_ROSTER = "Roster"

# Block Out Dates
FIELD_BLOCK_OUT_DATES = "Block Out Dates"
FIELD_UNCONFIRMED = "Unconfirmed"

# Member
FIELD_TELEGRAM_ID = "Telegram ID"
FIELD_FULL_NAME = "Full Name"
FIELD_NAME = "Name"
FIELD_DOB = "DOB"
FIELD_HP = "HP"
FIELD_CELL_GROUP = "Cell Group"
FIELD_CELL_LEADER = "Cell Leader"

FIELD_BAPTISED = "Baptised"
BAPTISED_YES = "Yes"
BAPTISED_NO = "No"

FIELD_ROLE = "Role"
ROLE_MINISTRY_HEAD = "Ministry Head"
ROLE_VICE_MINISTRY_HEAD = "Vice Ministry Head"
ROLE_LEADER = "Leader"
ROLE_MEMBER = "Member"

FIELD_COUNTING_ROOM_STATUS = "Counting Room Status"
COUNTING_ROOM_STATUS_NIL = "NIL"
COUNTING_ROOM_STATUS_SUBMITTED = "Submitted"
COUNTING_ROOM_STATUS_APPROVED = "Approved"
COUNTING_ROOM_STATUS_REJECTED = "Rejected"

FIELD_SERVING_STATUS = "Serving Status"
SERVING_STATUS_ACTIVE = "Active"
SERVING_STATUS_INACTIVE = "Inactive"
SERVING_STATUS_REMOVED = "Removed"
SERVING_STATUS_NEW_MEMBER = "New Member"


